### PR TITLE
Adding 418 I'm a droid.

### PR DESCRIPTION
**Pull request by ghchinoy**

### CODE REVIEW

**Comment by danielgsims** [comment]
I can't recall, is this actually a quote from the movie?

**Comment by kijanawoodard** [comment]
There's this:
http://starwars.wikia.com/wiki/Star_Wars_Episode_I:_I_Am_a_Droid

LOL

**Comment by danielgsims** [comment]
Awww man. Any other ideas?

**Comment by scottux** [comment]
@danielgsims Told ya we needed a 418.

**Comment by kijanawoodard** [comment]
"I am a Jedi, as my father was before me." [1]

"I am a member of the Imperial Senate on a diplomatic mission to Alderaan..." [2]

and, of course

"I am your father."

[1] http://thoughtcatalog.com/oliver-miller/2013/03/100-quotes-from-star-wars-in-order-of-awesomeness/

[2] http://www.imdb.com/title/tt0076759/quotes

**Comment by scottux** [comment]
I know there is a quote about short, but I don't know about stout :)

**Comment by danielgsims** [comment]
I like the Jedi quote :)

**Comment by jdpedrie** [comment]
+1. Even if it's not a direct quote, the star wars-esque twist on the status description makes it worthy of a merge.

**Comment by scottux** [comment]
"This is not the teapot you are looking for."

**Pull request merged**
